#!/usr/bin/perl -w
#
#
# build script to be used to unpack and test a dist tarball.
#
# builds in /tmp/heccer/<whatever>, and runs the tests.
#

use strict;


{
    # $Format: "system 'mkdir --parents \"/tmp/neurospaces/$ProjectVersion$\"'";$
system 'mkdir --parents "/tmp/${package}/${release_name}"'
}

if ($?)
{
    die "mkdir failed";
}


{
    # $Format: "system \"cp '/local_home/hugo/neurospaces/source/c/snapshots/0/neurospacesread-$ProjectVersion$.tar.gz' '/tmp/neurospaces/$ProjectVersion$'\"";$
system "cp '/local_home/hugo/${package}/source/c/snapshots/0/${package}-${release_name}.tar.gz' '/tmp/${package}/${release_name}'"
}

if ($?)
{
    die "cp failed";
}


{
    # $Format: "chdir \"/tmp/neurospaces/$ProjectVersion$\"";$
chdir "/tmp/${package}/${release_name}"
}

if ($?)
{
    die "chdir failed";
}


{
    # $Format: "system \"tar xfz 'neurospacesread-$ProjectVersion$.tar.gz'\"";$
system "tar xfz '${package}-${release_name}.tar.gz'"
}

if ($?)
{
    die "cp failed";
}


{
    # $Format: "chdir \"neurospacesread-$ProjectVersion$\"";$
chdir "${package}-${release_name}"
}

if ($?)
{
    die "chdir failed";
}


{
    # $Format: "system \"./configure\"";$
system "./configure"
}

if ($?)
{
    die "configure failed";
}


{
    # $Format: "system 'make'";$
system 'make'
}

if ($?)
{
    die "make failed";
}


{
    # $Format: "system 'make test'";$
system 'make test'
}

if ($?)
{
    die "test failed";
}

