#!/usr/bin/perl -w
#!/usr/bin/perl -d:ptkdb -w
#


use strict;


# read file

open my $fh, $ARGV[0]
    or die $!;

undef $/; # enable slurp mode

my $content = <$fh>;

close $fh;


# preserve empty lines delineating paragraphs

$content =~ s(^///\n)(/// \n)gm;

# process function headers

$content =~ s(/// \*+)()g;

# process function headers

$content =~ s(/// SHORT: .*\n///.*\n)()g;

# process return docs

$content =~ s(/// RTN..: )(/// \\return )g;

# process function descriptions

$content =~ s(/// DESCR: ([^\n]+))(/// \\brief $1\n///\n/// \\details )g;

# process notes docs

$content =~ s(///\s*NOTE\.:)(/// \\note )g;

# process arguments, up to 5 arguments

# $content =~ s(///\s*([a-zA-Z_]+)\S+)(/// \\arg $1)g;

$content =~ s((/// ARGS.:\s*\n///\s*\n(///\s+[^\n]+\n){0})///\s*([a-zA-Z_]+)\S+)($1/// \\arg $3)g;

$content =~ s((/// ARGS.:\s*\n///\s*\n(///\s+[^\n]+\n){1})///\s*([a-zA-Z_]+)\S+)($1/// \\arg $3)g;

$content =~ s((/// ARGS.:\s*\n///\s*\n(///\s+[^\n]+\n){2})///\s*([a-zA-Z_]+)\S+)($1/// \\arg $3)g;

$content =~ s((/// ARGS.:\s*\n///\s*\n(///\s+[^\n]+\n){3})///\s*([a-zA-Z_]+)\S+)($1/// \\arg $3)g;

$content =~ s((/// ARGS.:\s*\n///\s*\n(///\s+[^\n]+\n){4})///\s*([a-zA-Z_]+)\S+)($1/// \\arg $3)g;

$content =~ s(/// ARGS.:\s*\n)(///\n)g;


# remove all empty lines

$content =~ s(^///\n)()gm;

print $content;

