---
package:
  maintainer: hugo.cornelis@gmail.com
  name: heccer
releases:
  passive:
    '':
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: ''
      1:
        email: hugo.cornelis@gmail.com
        major: passive
        micro: 1
        minor: ''
      2:
        email: hugo.cornelis@gmail.com
        major: passive
        micro: 2
        minor: ''
    1:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 1
    10:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 10
    11:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 11
    12:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 12
    13:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 13
    14:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 14
    15:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 15
    16:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 16
    17:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 17
    18:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 18
    19:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 19
    2:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 2
    20:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 20
    21:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 21
    22:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 22
    23:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 23
    24:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 24
    25:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 25
    26:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 26
    27:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 27
    3:
      1:
        email: hugo.cornelis@gmail.com
        major: passive
        micro: 1
        minor: 3
    4:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 4
    5:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 5
    6:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 6
    7:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 7
    8:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 8
    9:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 9
