---
package:
  maintainer: hugo.cornelis@gmail.com
  name: heccer
releases:
  passive:
    1:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 1
    2:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 2
