---
package:
  maintainer: hugo.cornelis@gmail.com
  name: heccer
releases:
  active:
    1:
      '':
        email: hugo.cornelis@gmail.com
        major: active
        micro: ''
        minor: 1
    2: {}
    3:
      '':
        email: hugo.cornelis@gmail.com
        major: active
        micro: ''
        minor: 3
    4: {}
  integration:
    1:
      '':
        email: hugo.cornelis@gmail.com
        major: integration
        micro: ''
        minor: 1
  passive:
    '':
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: ''
      1:
        email: hugo.cornelis@gmail.com
        major: passive
        micro: 1
        minor: ''
      2:
        email: hugo.cornelis@gmail.com
        major: passive
        micro: 2
        minor: ''
    1:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 1
    10:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 10
    11:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 11
    12:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 12
    13:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 13
    14:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 14
    15:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 15
    16:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 16
    17:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 17
    18:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 18
    19:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 19
    2:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 2
    20:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 20
    21:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 21
    22:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 22
    23:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 23
    24:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 24
    25:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 25
    26:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 26
    27:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 27
    3:
      1:
        email: hugo.cornelis@gmail.com
        major: passive
        micro: 1
        minor: 3
    4:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 4
    5:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 5
    6:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 6
    7:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 7
    8:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 8
    9:
      '':
        email: hugo.cornelis@gmail.com
        major: passive
        micro: ''
        minor: 9
  pools:
    1:
      '':
        email: hugo.cornelis@gmail.com
        major: pools
        micro: ''
        minor: 1
    10:
      pre-release:
        email: hugo.cornelis@gmail.com
        major: pools
        micro: pre-release
        minor: 10
    2: {}
    3:
      '':
        email: hugo.cornelis@gmail.com
        major: pools
        micro: ''
        minor: 3
    4: {}
    5:
      '':
        email: hugo.cornelis@gmail.com
        major: pools
        micro: ''
        minor: 5
    6:
      '':
        email: hugo.cornelis@gmail.com
        major: pools
        micro: ''
        minor: 6
    7:
      '':
        email: hugo.cornelis@gmail.com
        major: pools
        micro: ''
        minor: 7
    8:
      '':
        email: hugo.cornelis@gmail.com
        major: pools
        micro: ''
        minor: 8
      pre-release:
        email: hugo.cornelis@gmail.com
        major: pools
        micro: pre-release
        minor: 8
    9:
      '':
        email: hugo.cornelis@gmail.com
        major: pools
        micro: ''
        minor: 9
  swig:
    1:
      '':
        email: hugo.cornelis@gmail.com
        major: swig
        micro: ''
        minor: 1
    2:
      '':
        email: hugo.cornelis@gmail.com
        major: swig
        micro: ''
        minor: 2
    3:
      '':
        email: hugo.cornelis@gmail.com
        major: swig
        micro: ''
        minor: 3
    4:
      '':
        email: hugo.cornelis@gmail.com
        major: swig
        micro: ''
        minor: 4
    5:
      '':
        email: hugo.cornelis@gmail.com
        major: swig
        micro: ''
        minor: 5
    6:
      '':
        email: hugo.cornelis@gmail.com
        major: swig
        micro: ''
        minor: 6
      pre-release:
        email: hugo.cornelis@gmail.com
        major: swig
        micro: pre-release
        minor: 6
    7:
      '':
        email: hugo.cornelis@gmail.com
        major: swig
        micro: ''
        minor: 7
    8:
      pre-release:
        email: hugo.cornelis@gmail.com
        major: swig
        micro: pre-release
        minor: 8
  tabulation:
    '':
      '':
        email: hugo.cornelis@gmail.com
        major: tabulation
        micro: ''
        minor: ''
    1:
      '':
        email: hugo.cornelis@gmail.com
        major: tabulation
        micro: ''
        minor: 1
    2:
      '':
        email: hugo.cornelis@gmail.com
        major: tabulation
        micro: ''
        minor: 2
    3:
      '':
        email: hugo.cornelis@gmail.com
        major: tabulation
        micro: ''
        minor: 3
    4:
      '':
        email: hugo.cornelis@gmail.com
        major: tabulation
        micro: ''
        minor: 4
    5: {}
    6:
      '':
        email: hugo.cornelis@gmail.com
        major: tabulation
        micro: ''
        minor: 6
    7: {}
    8:
      '':
        email: hugo.cornelis@gmail.com
        major: tabulation
        micro: ''
        minor: 8
    9: {}
