#!/usr/bin/perl -w
#!/usr/bin/perl -d:ptkdb -w
#
##
## Heccer : a compartmental solver that implements efficient Crank-Nicolson
## integration for neuronal models.
##

##############################################################################
##'
##' Heccer : testbed C implementation
##'
##' Copyright (C) 2006-2008 Hugo Cornelis
##'
##' functional ideas ..	Hugo Cornelis, hugo.cornelis@gmail.com
##'
##' coding ............	Hugo Cornelis, hugo.cornelis@gmail.com
##'
##############################################################################


use strict;


BEGIN
{
    # during tests

    push @INC, '../glue/swig/perl';

    # during distcheck

    push @INC, '../../glue/swig/perl';

    # after installation

    push @INC, '/usr/local/glue/swig/perl';
}


BEGIN
{
    # for main during tests

    push @INC, 'tests/glue/swig/perl';

    # for main during check

    push @INC, './glue/swig/perl';

    # for main during distcheck

    push @INC, '../../tests/glue/swig/perl';
}


use Heccer;


# initialize compartments

my $compartments
    = [
       {
	dCm => 4.57537e-11,
	dEm => -0.08,
	dInitVm => -0.068,
	dInject => 0,
	dRa => 360502,
	dRm => 3.58441e+08,
	iParent => -1,
       },
       {
	dCm => 4.57537e-11,
	dEm => -0.08,
	dInitVm => -0.068,
	dInject => 0,
	dRa => 360502,
	dRm => 3.58441e+08,
	iParent => 0,
       },
       {
	dCm => 4.57537e-11,
	dEm => -0.08,
	dInitVm => -0.068,
	dInject => 0,
	dRa => 360502,
	dRm => 3.58441e+08,
	iParent => 1,
       },
       {
	dCm => 4.57537e-11,
	dEm => -0.08,
	dInitVm => -0.068,
	dInject => 0,
	dRa => 360502,
	dRm => 3.58441e+08,
	iParent => 0,
       },
      ];

# initialize intermediary

our $intermediary
    = Heccer::Intermediary->new
      (
       {
	comp2mech => [ 0, 0, 0, 0, -1],
	compartments => $compartments,
	iCompartments => 4,
       },
      );


# require 'main';


use Data::Dumper;

use Heccer;


our $config;

$config->{defaults}
    = {
       concentration_gate_end => 0.3,
       concentration_gate_start => 4e-5,
       interval_default_end => (0.05),
       interval_default_entries => 3000,
       interval_default_start => (-0.1),
       reporting_granularity => 1,
       steps => 10,
       tested_things => $SwiggableHeccer::HECCER_DUMP_ALL,
       time_step => (2e-5),
      };

# initialize options

my $options
    = Heccer::Options->new
      (
       {
	dConcentrationGateEnd => $config->{settings}->{concentration_gate_end} || $config->{defaults}->{concentration_gate_end},
	dConcentrationGateStart => $config->{settings}->{concentration_gate_start} || $config->{defaults}->{concentration_gate_start},
	dIntervalEnd => $config->{settings}->{interval_default_end} || $config->{defaults}->{interval_default_end},
	dIntervalStart => $config->{settings}->{interval_default_start} || $config->{defaults}->{interval_default_start},
	iIntervalEntries => $config->{settings}->{interval_default_entries} || $config->{defaults}->{interval_default_entries},
       },
      );

# instantiate heccer

my $step = $config->{settings}->{time_step} || $config->{defaults}->{time_step};

our $intermediary;

my $heccer
    = Heccer->new
      (
       {
	dStep => $step,
	intermediary => $intermediary,
	options => $options,
       },
      );

# build indices for optimization, compile to byte code

$heccer->compile();

# initiate values

$heccer->initiate();

# initial dump

print "Initiated\n";

$heccer->dump($config->{settings}->{tested_things} || $config->{defaults}->{tested_things});

# a couple of times

my $final_report = 0;

foreach my $i (0 .. ($config->{settings}->{steps} || $config->{defaults}->{steps}) - 1)
{
    # update the current simulation time.

    # + 1e-9 needs to be configurable

    my $time = $i * $step + 1e-9;

    # step

    $heccer->hecc($time);

    if (($i % ($config->{settings}->{reporting_granularity} || $config->{defaults}->{reporting_granularity})) == 0)
    {
	# dump

	print "-------\n";

	print "Iteration $i\n";

	$heccer->dump($config->{settings}->{tested_things} || $config->{defaults}->{tested_things});
    }
    else
    {
	$final_report = 1;
    }
}

if ($final_report)
{
    $heccer->dump();
}


1;



